const JOB_DB='gdrive-video-staging',JOB_STORE='jobs';
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(JOB_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(JOB_STORE))db.createObjectStore(JOB_STORE);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('Could not open local staging storage.'));});}
async function put(key,value){const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction(JOB_STORE,'readwrite');tx.objectStore(JOB_STORE).put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||new Error('Could not save staged data.'));});db.close();}
async function get(key){const db=await openDB();const value=await new Promise((resolve,reject)=>{const tx=db.transaction(JOB_STORE,'readonly');const req=tx.objectStore(JOB_STORE).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('Could not read staged job.'));});db.close();return value;}
async function del(key){const db=await openDB();await new Promise(resolve=>{const tx=db.transaction(JOB_STORE,'readwrite');tx.objectStore(JOB_STORE).delete(key);tx.oncomplete=resolve;tx.onerror=tx.onabort=resolve;});db.close();}
function send(type,payload={}){try{chrome.runtime.sendMessage({type,...payload});}catch(_){} }
function makeFullRangeURL(url){if(!url)return url;try{const u=new URL(url),clen=Number(u.searchParams.get('clen'));if(Number.isSafeInteger(clen)&&clen>0)u.searchParams.set('range',`0-${clen-1}`);return u.toString();}catch(_){return url;}}
async function fetchToBlob(url,label,jobId,signal,expectedTotal=0){const response=await fetch(makeFullRangeURL(url),{credentials:'include',cache:'no-store',signal});if(!response.ok)throw new Error(`${label} request failed (${response.status})`);const contentRange=response.headers.get('content-range')||'',rangeMatch=contentRange.match(/\/([0-9]+)\s*$/),total=(rangeMatch?Number(rangeMatch[1]):0)||Number(response.headers.get('content-length'))||Number(expectedTotal)||0,reader=response.body?.getReader?.();if(!reader){const blob=await response.blob();send('videoStageProgress',{jobId,label,received:blob.size,total:total||blob.size});return blob;}const chunks=[];let received=0,lastReport=0;while(true){const{done,value}=await reader.read();if(done)break;if(value){chunks.push(value);received+=value.byteLength;const now=performance.now();if(now-lastReport>=100||(total&&received>=total)){lastReport=now;send('videoStageProgress',{jobId,label,received,total});}}}send('videoStageProgress',{jobId,label,received,total});return new Blob(chunks);}
let currentJobId=null,cancelled=false,videoController=null,audioController=null,activeWorker=null;
chrome.runtime.onMessage.addListener(message=>{if(message?.target==='video-offscreen'&&message.type==='videoStageStart'){run(message.jobId).catch(error=>finishError(message.jobId,error));}if(message?.target==='video-offscreen'&&message.type==='videoStageCancelInternal'){cancelled=true;try{videoController?.abort();}catch(_){}try{audioController?.abort();}catch(_){}try{activeWorker?.terminate();}catch(_){}videoController=null;audioController=null;activeWorker=null;}});
function isAbortError(error){return cancelled||error?.name==='AbortError'||/aborted|abort/i.test(String(error?.message||error||''));}
function finishError(jobId,error){const payload={jobId,message:error?.message||String(error)};send(isAbortError(error)?'videoStageCancelled':'videoStageError',payload);}
async function getJob(jobId){return await new Promise((resolve,reject)=>{chrome.runtime.sendMessage({type:'getVideoStageJob',jobId},response=>{if(chrome.runtime.lastError)reject(new Error(chrome.runtime.lastError.message));else if(!response?.job)reject(new Error(response?.error||'Staging job was not found.'));else resolve(response.job);});});}
async function triggerDownload(blob,filename,jobId){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.rel='noopener';a.style.display='none';document.body.appendChild(a);a.click();a.remove();send('videoStageDownloadStarted',{jobId});setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function run(jobId){currentJobId=jobId;cancelled=false;const job=await getJob(jobId);send('videoStageStatus',{jobId,stage:'download',message:'Downloading full video and audio streams…'});videoController=new AbortController();audioController=new AbortController();const[videoBlob,audioBlob]=await Promise.all([fetchToBlob(job.videoUrl,'video',jobId,videoController.signal,job.videoBytes||0),fetchToBlob(job.audioUrl,'audio',jobId,audioController.signal,job.audioBytes||0)]);videoController=null;audioController=null;if(cancelled)throw Object.assign(new Error('Download cancelled.'),{name:'AbortError'});send('videoStageStatus',{jobId,stage:'staged'});await put(`video:${jobId}`,videoBlob);await put(`audio:${jobId}`,audioBlob);if(cancelled)throw Object.assign(new Error('Download cancelled.'),{name:'AbortError'});const worker=new Worker(chrome.runtime.getURL('vendor/ffmpeg-mux-worker.js'));activeWorker=worker;let done;try{done=await new Promise((resolve,reject)=>{worker.onmessage=async e=>{const data=e.data||{};if(data.type==='source-progress')send('videoStageProgress',{jobId,label:data.label,received:data.received,total:data.total});else if(data.type==='status')send('videoStageStatus',{jobId,stage:'merge',message:data.message});else if(data.type==='ffmpeg-log')send('videoStageLog',{jobId,message:data.message});else if(data.type==='ffmpeg-progress')send('videoStageMergeProgress',{jobId,progress:Math.max(0,Math.min(1,Number(data.progress)||0)),mergeTimeUs:Number(data.time)||0,mergeDurationUs:Number(data.duration)||0,frame:Number(data.frame)||0});else if(data.type==='done')resolve(data.blob);else if(data.type==='error')reject(new Error(data.message||'FFmpeg failed.'));};worker.onerror=e=>reject(new Error(e.message||'FFmpeg worker failed.'));let audioCodec='';try{const u=new URL(job.audioUrl),codecs=u.searchParams.get('codecs')||'',mime=u.searchParams.get('mime')||'';if(/mp4a/i.test(codecs)||/audio\/mp4/i.test(mime))audioCodec='aac';}catch(_){}worker.postMessage({type:'mux',video:videoBlob,audio:audioBlob,audioCodec});});}finally{try{worker.terminate();}catch(_){}activeWorker=null;}if(cancelled)throw Object.assign(new Error('Download cancelled.'),{name:'AbortError'});await put(`output:${jobId}`,done);await del(`video:${jobId}`);await del(`audio:${jobId}`);send('videoStageStatus',{jobId,stage:'processing'});if(cancelled)throw Object.assign(new Error('Download cancelled.'),{name:'AbortError'});const output=await get(`output:${jobId}`);if(!(output instanceof Blob))throw new Error('Merged MP4 was not found in local staging.');await triggerDownload(output,job.filename,jobId);send('videoStageFinished',{jobId});await del(`output:${jobId}`);}
